{% set name = "phono3py" %}
{% set version = "2.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b91f154469b6905933a19f3d315b638b2e6882651d7ffc02c171e4e1f719d89a

build:
  number: 0
  script: echo "[phono3py]\nextra_compile_args = -fopenmp\nextra_link_args = -lgomp" > site.cfg && {{ PYTHON }} -m pip install . -vv
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
  host:
    - python 
    - pip
    - numpy
    - libblas
    - libcblas
    - liblapacke
    - libgfortran
    - openblas
    - mkl
  run:
    - python
    - pip
    - scipy
    - pyyaml
    - matplotlib-base
    - h5py
    - phonopy >=2.9.3
    - libblas * *openblas
    - openblas
    - libgfortran-ng  # [linux]
    - llvm-openmp  # [osx]
    - _openmp_mutex  # [linux]

test:
  imports:
    - phono3py
  commands:
    - pip check

about:
  home: https://atztogo.github.io/phono3py
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A simulation package of phonon-phonon interaction related properties

  description: |
    This software calculates phonon-phonon interaction and related 
    properties using the supercell approach. 
  doc_url: https://atztogo.github.io/phono3py
  dev_url: https://github.com/atztogo/phono3py

extra:
  recipe-maintainers:
    - jan-janssen
    - jochym
    - atztogo
