{% set name = "phono3py" %}
{% set version = "1.22.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/phonopy/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 3284bf7af5c4d870760a18f43d1c6f8e796547d51e8d921ebf3833ebc908a9b3

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - numpy
    - libblas
    - libcblas
    - liblapacke
    - libgfortran
    - openblas
  run:
    - python
    - pip
    - scipy
    - pyyaml
    - matplotlib-base
    - h5py
    - phonopy >=2.8.1
    - libblas * *openblas
    - openblas
    - libgfortran-ng  # [linux]
    - llvm-openmp  # [osx]
    - _openmp_mutex  # [linux]

test:
  imports:
    - phono3py
  commands:
    - pip check

about:
  home: https://atztogo.github.io/phono3py
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A simulation package of phonon-phonon interaction related properties

  description: |
    This software calculates phonon-phonon interaction and related 
    properties using the supercell approach. 
  doc_url: https://atztogo.github.io/phono3py
  dev_url: https://github.com/atztogo/phono3py

extra:
  recipe-maintainers:
    - jan-janssen
    - jochym
