{% set name = "phono3py" %}
{% set version = "2.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1932e1d96ec3a26a19709e9e52a11397d852989b717d35d5c09313cb3a6d1a6d

build:
  number: 0
  script: echo "[phono3py]" > site.cfg && echo "extra_compile_args = -fopenmp" >> site.cfg && echo "extra_link_args = -lgomp" >> site.cfg && {{ PYTHON }} -m pip install . -vv
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
  host:
    - python
    - pip
    - numpy >=1.15.0
    - libblas
    - libcblas
    - libgfortran
    - openblas
  run:
    - python
    - scipy
    - pyyaml
    - matplotlib-base >=2.2.2
    - h5py
    - phonopy >=2.14.0
    - openblas

test:
  imports:
    - phono3py
  commands:
    - pip check
    - phono3py --help
  requires:
    - pip

about:
  home: https://atztogo.github.io/phono3py
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A simulation package of phonon-phonon interaction related properties

  description: |
    This software calculates phonon-phonon interaction and related 
    properties using the supercell approach. 
  doc_url: https://phonopy.github.io/phono3py
  dev_url: https://github.com/phonopy/phono3py

extra:
  recipe-maintainers:
    - jan-janssen
    - jochym
    - atztogo
