travis:
  secure:
    BINSTAR_TOKEN: f5PmsbFwGVcOn0zgUCQdH+B06r8ALox1n8cFdjuDh9DdWOOWzhd1aADyJC0BFEZ+xgX2wombBd7hz0OPbkTozSp8MtwCm+29oWbLQ1BL0hG7YZ+c0YEkuo3KkqHc69dq+kl7OH0ge42ouVBDdp2NG0vJihnkPRWNfXg7lmbv7KqZnJhP9K0UPLFVoCmwt8kCEjuVrUFcm0z7LzLsGw1K9Av2q1VOhNdvSw1OR9hsPoHc+HPfWqI8liAwkLtYw1FhpTaZyrsP+JRAcc6iTL5qgt5mgagNqeJG+sF3FRYWno33YCj5sVAimzJ00cBghmUuXAfe5oLfxt5IUc9aeOhoZuTzKW4OZpSaepFYB5H21cWBfMb58ZnIazTbM1L5grTzpx/5yViUtedlYdC6N74bkJxjKvBRpMiJAAHcOyFGHssytC1jr9Dej//dCSvjq7oBU9iR4MbFEdzo66LPfPD9ri6VkeX+gUGwbzQ0TDWn+rdMJoh/5W8c6w+Dnq3FtcS0kM+Z8sPPL86y8iozIAWqxofK14eko7Ha1KzTDNcGADBsEZbpQv/WUjWUQoWP3ur7ipLs1oiTImiB7UkJmOb4BqO20fC2k15Wmj3XOJVJISAqaMRJiNDoDBCmOZD399KdjqLqRTgnA15n4VIWMj2BvBEhzy63p8WIttjdjHUYsyY=
bot:
  automerge: true
conda_forge_output_validation: true
